import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.165.0/build/three.module.js';
import { OrbitControls } from 'https://cdn.jsdelivr.net/npm/three@0.165.0/examples/jsm/controls/OrbitControls.js';

const COLORS={White:'#f8fafc',Yellow:'#facc15',Red:'#ef4444',Orange:'#f97316',Blue:'#3b82f6',Green:'#22c55e'}, EMPTY='#273147';
const FACES=[
 {key:'F',name:'Front',color:'Green',cue:'1 · START HERE',arrow:'◎'},
 {key:'U',name:'Top',color:'White',cue:'2 · ROTATE',arrow:'↓'},
 {key:'R',name:'Right',color:'Red',cue:'3 · ROTATE',arrow:'←'},
 {key:'D',name:'Bottom',color:'Yellow',cue:'4 · ROTATE',arrow:'↑'},
 {key:'L',name:'Left',color:'Orange',cue:'5 · ROTATE',arrow:'→'},
 {key:'B',name:'Back',color:'Blue',cue:'6 · ROTATE',arrow:'↻'}
];
const face=Object.fromEntries(FACES.map(x=>[x.key,x])), $=s=>document.querySelector(s);
let size=3,active='F',paint='Green',state={},saved=new Set(),solution=[],moveAt=-1,solving=false,solverReady=false,message=null;
let scene,camera,renderer,controls,cube,cubies=[];
const current=()=>FACES.findIndex(x=>x.key===active), full=k=>state[k].every(Boolean), colorCount=c=>Object.values(state).flat().filter(x=>x===c).length;
function reset(){state=Object.fromEntries(FACES.map(x=>[x.key,Array(size*size).fill(null)]));saved=new Set();solution=[];moveAt=-1;solving=false;message=null}
function render(){
 $('.size-btns').innerHTML=[2,3,4].map(n=>`<button class="size ${n===size?'on':''}" data-size="${n}">${n} × ${n}</button>`).join('');
 $('.size-btns').querySelectorAll('button').forEach(b=>b.onclick=()=>{size=+b.dataset.size;active='F';paint='Green';reset();buildCube();render();say('New blank cube ready')});
 $('#scan-rail').innerHTML=FACES.map((x,i)=>`<button data-face="${x.key}" ${i<=current()||saved.has(x.key)?'':'disabled'} class="stop ${active===x.key?'on':''} ${saved.has(x.key)?'done':''}"><i style="--c:${COLORS[x.color]}">${saved.has(x.key)?'✓':i+1}</i>${x.name}</button>`).join('');
 $('#scan-rail').querySelectorAll('button').forEach(b=>b.onclick=()=>{active=b.dataset.face;render();showScanFace(active)});
 $('#palette').innerHTML=Object.entries(COLORS).map(([n,c])=>`<button class="swatch ${n===paint?'on':''}" data-color="${n}"><i style="background:${c}"></i>${n}</button>`).join('');
 $('#palette').querySelectorAll('button').forEach(b=>b.onclick=()=>{paint=b.dataset.color;render()});
 const x=face[active],i=current(),count=state[active].filter(Boolean).length;
 $('#scan-count').textContent=`${saved.size} / 6 saved`;$('#face-title').textContent=`${x.name} face`;$('#face-count').textContent=`${count} / ${size*size}`;$('#scan-cue').textContent='';$('#scan-tip').innerHTML='';$('#scan-tip').closest('.scan-card').style.display='none';$('#preview-name').textContent=x.name;
 $('#face-grid').style.gridTemplateColumns=`repeat(${size},1fr)`;$('#face-grid').innerHTML=state[active].map((c,n)=>`<button class="cell" data-cell="${n}" style="background:${c?COLORS[c]:EMPTY}"></button>`).join('');
 $('#face-grid').querySelectorAll('button').forEach(b=>b.onclick=()=>{state[active][+b.dataset.cell]=paint;saved.delete(active);solution=[];moveAt=-1;message=null;sync();render()});
 $('#previous-face').disabled=i===0;$('#previous-face').onclick=()=>{if(i){active=FACES[i-1].key;render();showScanFace(active)}};
 const next=$('#save-next'),missing=size*size-count;next.disabled=!!missing;next.textContent=missing?`Fill ${missing} more`:i===5?'Validate & solve →':`Save ${x.name} & continue →`;next.onclick=()=>{if(!full(active))return;saved.add(active);if(i<5){active=FACES[i+1].key;render();showScanFace(active);say(`${face[FACES[i].key].name} saved ✓`)}else{showScanFace('F');render();solve()}};renderSolution()
}
function renderSolution(){let title='Awaiting scan',copy='Save each face in order. Future faces stay locked until it is their turn.';if(saved.size===6&&size!==3){title='3×3 solve only';copy='Scanning and the live preview work for all sizes. A reliable browser solver is enabled for 3×3 only.'}if(solving){title='Checking cube…';copy='Validating colors and calculating an efficient solve. First use may take a few seconds.'}if(message){title=message.title;copy=message.copy}if(solution.length){title=`${solution.length} moves ready`;copy='A computer-optimized route. Use arrows to animate every move forward or backward.'}$('#solution-status').textContent=title;$('#solution-copy').textContent=copy;$('#progress').textContent=solution.length?`${Math.max(0,moveAt+1)} / ${solution.length}`:'—';$('#previous-move').disabled=!solution.length||moveAt<0;$('#next-move').disabled=!solution.length||moveAt>=solution.length-1}
function valid(){if(new Set(FACES.map(x=>state[x.key][4])).size!==6)return'Each center square must use a different color.';for(const c of Object.keys(COLORS))if(colorCount(c)!==9)return`You need exactly 9 ${c.toLowerCase()} stickers; this scan has ${colorCount(c)}.`;return null}
function load(src){return new Promise((yes,no)=>{let s=document.createElement('script');s.src=src;s.onload=yes;s.onerror=()=>no(Error('solver download failed'));document.head.append(s)})}
function facelets(){const centers=Object.fromEntries(FACES.map(x=>[state[x.key][4],x.key]));return['U','R','F','D','L','B'].flatMap(k=>state[k].map(c=>centers[c])).join('')}
function exactShortSolve(){const moves=['U',"U'",'U2','R',"R'",'R2','F',"F'",'F2','D',"D'",'D2','L',"L'",'L2','B',"B'",'B2'],root=Cube.fromString(facelets());function search(node,depth,last,path){if(node.isSolved())return path;if(!depth)return null;for(const move of moves){if(move[0]===last)continue;const next=new Cube(node);next.move(move);const found=search(next,depth-1,move[0],[...path,move]);if(found)return found}return null}for(let depth=1;depth<=4;depth++){const found=search(root,depth,'',[]);if(found)return found}return null}
async function solve(){if(size!==3||solving)return;let problem=valid();if(problem){message={title:'Scan needs review',copy:problem};renderSolution();return}if(FACES.every(x=>state[x.key].every(c=>c===state[x.key][4]))){solution=[];moveAt=-1;message={title:'Already solved',copy:'Nice — every face is already uniform. There are no moves to make.'};renderSolution();return}solving=true;message=null;renderSolution();try{if(!window.Cube){await load('https://cdn.jsdelivr.net/npm/cubejs@1.3.2/lib/cube.js');await load('https://cdn.jsdelivr.net/npm/cubejs@1.3.2/lib/solve.js')}if(!solverReady){window.Cube.initSolver();solverReady=true}solution=exactShortSolve()||window.Cube.fromString(facelets()).solve().trim().split(/\s+/);moveAt=-1;if(!solution.length)message={title:'Already solved',copy:'Nice — every face is already uniform. There are no moves to make.'}}catch(e){console.warn(e);message={title:'Scan needs review',copy:'This does not form a legal cube in this orientation. Review the arrows and re-check the face colors.'}}finally{solving=false;renderSolution()}}
function reason(m,i){let phase=i<solution.length*.34?'sets up and preserves pieces already in place':i<solution.length*.72?'moves the remaining pieces into their correct positions':'finishes the last layer without undoing earlier work';let way=m.includes('2')?'twice':m.includes("'")?'counter-clockwise':'clockwise';return`${m[0]} turns ${way}; this ${phase}.`}
function inverse(m){return m.includes('2')?m:m.includes("'")?m[0]:m+"'"}
async function step(dir){let target=dir>0?moveAt+1:moveAt;if(target<0||target>=solution.length)return;await turn(dir>0?solution[target]:inverse(solution[target]));moveAt+=dir;say(dir>0?`Move ${moveAt+1}: ${solution[moveAt]} · ${reason(solution[moveAt],moveAt)}`:`Reversed move ${target+1}.`);renderSolution()}
function say(s){$('#move-readout').textContent=s}
function setup(){let stage=$('#cube-stage');scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(40,stage.clientWidth/stage.clientHeight,.1,100);camera.position.set(5.5,4.8,6.8);renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));stage.replaceChildren(renderer.domElement);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.target.set(0,0,0);controls.minDistance=4;controls.maxDistance=12;scene.add(new THREE.HemisphereLight(0xf4f7ff,0x8492b6,3.1));let key=new THREE.DirectionalLight(0xffffff,3.6);key.position.set(5,7,6);scene.add(key);let fill=new THREE.PointLight(0x92a9ff,18,18);fill.position.set(-4,-4,5);scene.add(fill);let rim=new THREE.PointLight(0x805cff,13,18);rim.position.set(-5,4,-4);scene.add(rim);addEventListener('resize',()=>{camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix();renderer.setSize(stage.clientWidth,stage.clientHeight)});(function tick(){requestAnimationFrame(tick);controls.update();renderer.render(scene,camera)})()}
const mat=c=>new THREE.MeshStandardMaterial({color:c,roughness:.3,metalness:.08});
function buildCube(){if(cube)scene.remove(cube);cube=new THREE.Group();cubies=[];let mid=(size-1)/2,dark=mat(0x141925),at=(r,c)=>r*size+c;for(let x=0;x<size;x++)for(let y=0;y<size;y++)for(let z=0;z<size;z++){let p=new THREE.Group();p.add(new THREE.Mesh(new THREE.BoxGeometry(.93,.93,.93),dark));let add=(pos,rot,f,n)=>{let s=new THREE.Mesh(new THREE.PlaneGeometry(.77,.77),mat(COLORS[state[f]?.[n]]||EMPTY));s.position.copy(pos);s.rotation.set(...rot);s.userData={f,n};p.add(s)};if(z===size-1)add(new THREE.Vector3(0,0,.466),[0,0,0],'F',at(size-1-y,x));if(z===0)add(new THREE.Vector3(0,0,-.466),[0,Math.PI,0],'B',at(size-1-y,size-1-x));if(y===size-1)add(new THREE.Vector3(0,.466,0),[-Math.PI/2,0,0],'U',at(z,x));if(y===0)add(new THREE.Vector3(0,-.466,0),[Math.PI/2,0,0],'D',at(size-1-z,x));if(x===size-1)add(new THREE.Vector3(.466,0,0),[0,Math.PI/2,0],'R',at(size-1-y,size-1-z));if(x===0)add(new THREE.Vector3(-.466,0,0),[0,-Math.PI/2,0],'L',at(size-1-y,z));p.position.set(x-mid,y-mid,z-mid);cube.add(p);cubies.push(p)}scene.add(cube);$('#cube-title').textContent=`${size} × ${size} interactive cube`}
function sync(){cubies.forEach(p=>p.children.forEach(m=>{if(m.userData.f)m.material.color.set(COLORS[state[m.userData.f][m.userData.n]]||EMPTY)}))}
function showScanFace(key){const target={F:[0,0,0],U:[Math.PI/2,0,0],R:[0,-Math.PI/2,0],D:[-Math.PI/2,0,0],L:[0,Math.PI/2,0],B:[0,Math.PI,0]}[key],from=cube.rotation.clone(),center=[0,0,0],started=performance.now(),duration=2300;function ease(now){const p=Math.min((now-started)/duration,1),first=p<.52,raw=first?p/.52:(p-.52)/.48,local=1-(1-raw)**3,source=first?[from.x,from.y,from.z]:center,dest=first?center:target;cube.rotation.set(source[0]+(dest[0]-source[0])*local,source[1]+(dest[1]-source[1])*local,source[2]+(dest[2]-source[2])*local);if(p<1)requestAnimationFrame(ease)}requestAnimationFrame(ease)}
function turn(m){let f=m[0],axis={R:'x',L:'x',U:'y',D:'y',F:'z',B:'z'}[f],side={R:1,L:-1,U:1,D:-1,F:1,B:-1}[f]*((size-1)/2),layer=cubies.filter(p=>Math.abs(p.position[axis]-side)<.1),pivot=new THREE.Group();layer.forEach(p=>pivot.attach(p));cube.add(pivot);let sign=(f==='L'||f==='D'||f==='B'?1:-1)*(m.includes("'")?-1:1),angle=sign*Math.PI/2*(m.includes('2')?2:1),start=performance.now();return new Promise(done=>{let go=t=>{let p=Math.min((t-start)/430,1);pivot.rotation[axis]=angle*(1-(1-p)**3);if(p<1)requestAnimationFrame(go);else{pivot.updateMatrixWorld();[...pivot.children].forEach(p=>cube.attach(p));cube.remove(pivot);done()}};requestAnimationFrame(go)})}
const flair=document.createElement('style');flair.textContent='.stage{box-shadow:0 0 0 1px #a9a4ff1c,0 28px 80px #493dba35}.stage:after{content:"";position:absolute;inset:-35%;pointer-events:none;background:conic-gradient(from 120deg,transparent,#776eff16,transparent 34%);animation:cubeflowGlow 9s linear infinite}@keyframes cubeflowGlow{to{transform:rotate(360deg)}}.mark{box-shadow:0 0 28px #7d73ff88}.swatch.on{animation:colorPulse 1.6s ease-in-out infinite}@keyframes colorPulse{50%{box-shadow:0 0 0 4px #756df5,0 0 20px #8d85ff}}.signature{margin-left:7px;padding-left:12px;border-left:1px solid #aeb9ee40;color:#c7c4ff;font:500 11px "DM Mono",monospace;letter-spacing:.08em;font-style:italic;white-space:nowrap}.signature span{color:#8c96b8;font-size:9px;font-style:normal;text-transform:uppercase;letter-spacing:.13em}';document.head.append(flair);const signature=document.createElement('div');signature.className='signature';signature.innerHTML='<span>crafted by</span><br>Joel Philip';document.querySelector('.brand').append(signature);
$('#start-over').onclick=()=>{if(confirm('Start over? This clears every scanned face.')){reset();active='F';sync();showScanFace('F');render();say('New blank cube ready')}};$('#previous-move').onclick=()=>step(-1);$('#next-move').onclick=()=>step(1);reset();setup();buildCube();render();
